// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// c_assert_prob_matrix
bool c_assert_prob_matrix(const NumericMatrix& x, const std::string& mode);
RcppExport SEXP _survdistr_c_assert_prob_matrix(SEXP xSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(c_assert_prob_matrix(x, mode));
    return rcpp_result_gen;
END_RCPP
}
// c_interp_cif_mat
NumericMatrix c_interp_cif_mat(const NumericMatrix& x, const NumericVector& times, const NumericVector& eval_times);
RcppExport SEXP _survdistr_c_interp_cif_mat(SEXP xSEXP, SEXP timesSEXP, SEXP eval_timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eval_times(eval_timesSEXP);
    rcpp_result_gen = Rcpp::wrap(c_interp_cif_mat(x, times, eval_times));
    return rcpp_result_gen;
END_RCPP
}
// c_interp_surv_mat
NumericMatrix c_interp_surv_mat(const NumericMatrix& x, const NumericVector& times, const NumericVector& eval_times, const std::string& method);
RcppExport SEXP _survdistr_c_interp_surv_mat(SEXP xSEXP, SEXP timesSEXP, SEXP eval_timesSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eval_times(eval_timesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(c_interp_surv_mat(x, times, eval_times, method));
    return rcpp_result_gen;
END_RCPP
}
// c_disc_dens_to_surv_mat
NumericMatrix c_disc_dens_to_surv_mat(const NumericMatrix& x);
RcppExport SEXP _survdistr_c_disc_dens_to_surv_mat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(c_disc_dens_to_surv_mat(x));
    return rcpp_result_gen;
END_RCPP
}
// c_disc_haz_to_surv_mat
NumericMatrix c_disc_haz_to_surv_mat(const NumericMatrix& x);
RcppExport SEXP _survdistr_c_disc_haz_to_surv_mat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(c_disc_haz_to_surv_mat(x));
    return rcpp_result_gen;
END_RCPP
}
// c_cont_dens_to_surv_mat
NumericMatrix c_cont_dens_to_surv_mat(const NumericMatrix& x, const NumericVector& times);
RcppExport SEXP _survdistr_c_cont_dens_to_surv_mat(SEXP xSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(c_cont_dens_to_surv_mat(x, times));
    return rcpp_result_gen;
END_RCPP
}
// c_cont_haz_to_surv_mat
NumericMatrix c_cont_haz_to_surv_mat(const NumericMatrix& x, const NumericVector& times);
RcppExport SEXP _survdistr_c_cont_haz_to_surv_mat(SEXP xSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(c_cont_haz_to_surv_mat(x, times));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_survdistr_c_assert_prob_matrix", (DL_FUNC) &_survdistr_c_assert_prob_matrix, 2},
    {"_survdistr_c_interp_cif_mat", (DL_FUNC) &_survdistr_c_interp_cif_mat, 3},
    {"_survdistr_c_interp_surv_mat", (DL_FUNC) &_survdistr_c_interp_surv_mat, 4},
    {"_survdistr_c_disc_dens_to_surv_mat", (DL_FUNC) &_survdistr_c_disc_dens_to_surv_mat, 1},
    {"_survdistr_c_disc_haz_to_surv_mat", (DL_FUNC) &_survdistr_c_disc_haz_to_surv_mat, 1},
    {"_survdistr_c_cont_dens_to_surv_mat", (DL_FUNC) &_survdistr_c_cont_dens_to_surv_mat, 2},
    {"_survdistr_c_cont_haz_to_surv_mat", (DL_FUNC) &_survdistr_c_cont_haz_to_surv_mat, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_survdistr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
