// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// c_assert_prob_matrix
bool c_assert_prob_matrix(const NumericMatrix& x, const std::string& type);
RcppExport SEXP _survdistr_c_assert_prob_matrix(SEXP xSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(c_assert_prob_matrix(x, type));
    return rcpp_result_gen;
END_RCPP
}
// c_mat_interp
NumericMatrix c_mat_interp(const NumericMatrix& x, const NumericVector& times, const NumericVector& eval_times, bool constant, const std::string& type);
RcppExport SEXP _survdistr_c_mat_interp(SEXP xSEXP, SEXP timesSEXP, SEXP eval_timesSEXP, SEXP constantSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eval_times(eval_timesSEXP);
    Rcpp::traits::input_parameter< bool >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(c_mat_interp(x, times, eval_times, constant, type));
    return rcpp_result_gen;
END_RCPP
}
// c_vec_interp
NumericVector c_vec_interp(const NumericVector& x, const NumericVector& times, const NumericVector& eval_times, bool constant, const std::string& type);
RcppExport SEXP _survdistr_c_vec_interp(SEXP xSEXP, SEXP timesSEXP, SEXP eval_timesSEXP, SEXP constantSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eval_times(eval_timesSEXP);
    Rcpp::traits::input_parameter< bool >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(c_vec_interp(x, times, eval_times, constant, type));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_wcumsum_mat
NumericMatrix rcpp_wcumsum_mat(const NumericMatrix& x, const NumericVector& times);
RcppExport SEXP _survdistr_rcpp_wcumsum_mat(SEXP xSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_wcumsum_mat(x, times));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_wcumsum_mat_interp
NumericMatrix rcpp_wcumsum_mat_interp(const NumericMatrix& x, const NumericVector& times, const NumericVector& new_times);
RcppExport SEXP _survdistr_rcpp_wcumsum_mat_interp(SEXP xSEXP, SEXP timesSEXP, SEXP new_timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type new_times(new_timesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_wcumsum_mat_interp(x, times, new_times));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_survdistr_c_assert_prob_matrix", (DL_FUNC) &_survdistr_c_assert_prob_matrix, 2},
    {"_survdistr_c_mat_interp", (DL_FUNC) &_survdistr_c_mat_interp, 5},
    {"_survdistr_c_vec_interp", (DL_FUNC) &_survdistr_c_vec_interp, 5},
    {"_survdistr_rcpp_wcumsum_mat", (DL_FUNC) &_survdistr_rcpp_wcumsum_mat, 2},
    {"_survdistr_rcpp_wcumsum_mat_interp", (DL_FUNC) &_survdistr_rcpp_wcumsum_mat_interp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_survdistr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
