# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_assert_surv_matrix <- function(mat) {
    .Call(`_survdistr_rcpp_assert_surv_matrix`, mat)
}

c_surv_interp <- function(x, times, new_times, constant = TRUE) {
    .Call(`_survdistr_c_surv_interp`, x, times, new_times, constant)
}

c_surv_interp_scan <- function(x, times, new_times, constant = TRUE) {
    .Call(`_survdistr_c_surv_interp_scan`, x, times, new_times, constant)
}

rcpp_wcumsum_mat <- function(x, times) {
    .Call(`_survdistr_rcpp_wcumsum_mat`, x, times)
}

rcpp_wcumsum_mat_interp <- function(x, times, new_times) {
    .Call(`_survdistr_rcpp_wcumsum_mat_interp`, x, times, new_times)
}

