# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_assert_surv_matrix <- function(mat) {
    .Call(`_survdistr_rcpp_assert_surv_matrix`, mat)
}

c_mat_interp <- function(x, times, new_times, constant = TRUE, type = "surv") {
    .Call(`_survdistr_c_mat_interp`, x, times, new_times, constant, type)
}

rcpp_wcumsum_mat <- function(x, times) {
    .Call(`_survdistr_rcpp_wcumsum_mat`, x, times)
}

rcpp_wcumsum_mat_interp <- function(x, times, new_times) {
    .Call(`_survdistr_rcpp_wcumsum_mat_interp`, x, times, new_times)
}

